version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  blue:
    container_name: blue
    image: whereami2048/cheering_docker
    expose:
      - 8080
    ports:
      - "8080:8080"

  green:
    container_name: green
    image: whereami2048/cheering_docker
    expose:
      - 8080
    ports:
      - "8081:8080"