version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  spring:
    container_name: spring
    image: whereami2048/cheering_docker
    expose:
      - 8080
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    expose:
      - 61613
      - 15671
      - 15672
