spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cheering
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      show_sql: true
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: "localhost"
      password: "cldjfldQkdlxld1!"
      port: 6379

  cloud:
    aws:
      s3:
        bucket: "cheering"
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: "AKIA6ODU7ANOMQHHNGFF"
        secretKey: "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"

  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      #      location: /desktop/Cheering-BE/temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 10MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: ce1391987fa8b21273b262d6aaf9f507eae7d854d7604f492b259f47226f276d