ALTER TABLE meet_fan_tb DROP COLUMN nickname;

ALTER TABLE fan_tb ALTER COLUMN name TYPE VARCHAR(15);
ALTER TABLE fan_tb ALTER COLUMN name SET NOT NULL;

ALTER TABLE fan_tb ADD COLUMN meetName VARCHAR(15);

ALTER TABLE fan_tb ADD COLUMN meetImage VARCHAR(2000);

ALTER TABLE user_tb ALTER COLUMN name TYPE VARCHAR(15);
ALTER TABLE user_tb ALTER COLUMN name SET NOT NULL;