name: Develop_CI

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up main ENV
        run: |
          cd ./src/main/resources/
          touch ./application.yml
          echo "$ENV_PROPERTIES_LOCAL" > ./application.yml
        env:
          ENV_PROPERTIES_LOCAL: ${{ secrets.ENV_PROPERTIES_LOCAL }}

      - name: Set up test ENV
        run: |
          cd ./src/test/
          mkdir resources/
          cd resources/
          touch ./application.yml
          echo "$ENV_PROPERTIES_LOCAL" > ./application.yml
        env:
          ENV_PROPERTIES_LOCAL: ${{ secrets.ENV_PROPERTIES_LOCAL }}

      - name: Set up DB
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: 'Cheering'
          mysql user: 'root'
          mysql root password: ${{ secrets.TEST_DB_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
